//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KosoyPerEntityDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class klimovskii_kosoiEntities : DbContext
    {
        public klimovskii_kosoiEntities()
            : base("name=klimovskii_kosoiEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<wp_kosoicommentmeta> wp_kosoicommentmeta { get; set; }
        public DbSet<wp_kosoicomments> wp_kosoicomments { get; set; }
        public DbSet<wp_kosoilayerslider> wp_kosoilayerslider { get; set; }
        public DbSet<wp_kosoilinks> wp_kosoilinks { get; set; }
        public DbSet<wp_kosoioptions> wp_kosoioptions { get; set; }
        public DbSet<wp_kosoipostmeta> wp_kosoipostmeta { get; set; }
        public DbSet<wp_kosoiposts> wp_kosoiposts { get; set; }
        public DbSet<wp_kosoirevslider_css> wp_kosoirevslider_css { get; set; }
        public DbSet<wp_kosoirevslider_layer_animations> wp_kosoirevslider_layer_animations { get; set; }
        public DbSet<wp_kosoirevslider_settings> wp_kosoirevslider_settings { get; set; }
        public DbSet<wp_kosoirevslider_sliders> wp_kosoirevslider_sliders { get; set; }
        public DbSet<wp_kosoirevslider_slides> wp_kosoirevslider_slides { get; set; }
        public DbSet<wp_kosoirevslider_static_slides> wp_kosoirevslider_static_slides { get; set; }
        public DbSet<wp_kosoiterm_relationships> wp_kosoiterm_relationships { get; set; }
        public DbSet<wp_kosoiterm_taxonomy> wp_kosoiterm_taxonomy { get; set; }
        public DbSet<wp_kosoitermmeta> wp_kosoitermmeta { get; set; }
        public DbSet<wp_kosoiterms> wp_kosoiterms { get; set; }
        public DbSet<wp_kosoiusermeta> wp_kosoiusermeta { get; set; }
        public DbSet<wp_kosoiusers> wp_kosoiusers { get; set; }
        public DbSet<wp_kosoiwc_osmeta> wp_kosoiwc_osmeta { get; set; }
        public DbSet<wp_kosoiwoocommerce_api_keys> wp_kosoiwoocommerce_api_keys { get; set; }
        public DbSet<wp_kosoiwoocommerce_arr_log> wp_kosoiwoocommerce_arr_log { get; set; }
        public DbSet<wp_kosoiwoocommerce_attribute_taxonomies> wp_kosoiwoocommerce_attribute_taxonomies { get; set; }
        public DbSet<wp_kosoiwoocommerce_downloadable_product_permissions> wp_kosoiwoocommerce_downloadable_product_permissions { get; set; }
        public DbSet<wp_kosoiwoocommerce_order_itemmeta> wp_kosoiwoocommerce_order_itemmeta { get; set; }
        public DbSet<wp_kosoiwoocommerce_order_items> wp_kosoiwoocommerce_order_items { get; set; }
        public DbSet<wp_kosoiwoocommerce_order_status_action> wp_kosoiwoocommerce_order_status_action { get; set; }
        public DbSet<wp_kosoiwoocommerce_payment_tokenmeta> wp_kosoiwoocommerce_payment_tokenmeta { get; set; }
        public DbSet<wp_kosoiwoocommerce_payment_tokens> wp_kosoiwoocommerce_payment_tokens { get; set; }
        public DbSet<wp_kosoiwoocommerce_sessions> wp_kosoiwoocommerce_sessions { get; set; }
        public DbSet<wp_kosoiwoocommerce_shipping_zone_locations> wp_kosoiwoocommerce_shipping_zone_locations { get; set; }
        public DbSet<wp_kosoiwoocommerce_shipping_zone_methods> wp_kosoiwoocommerce_shipping_zone_methods { get; set; }
        public DbSet<wp_kosoiwoocommerce_shipping_zones> wp_kosoiwoocommerce_shipping_zones { get; set; }
        public DbSet<wp_kosoiwoocommerce_tax_rate_locations> wp_kosoiwoocommerce_tax_rate_locations { get; set; }
        public DbSet<wp_kosoiwoocommerce_tax_rates> wp_kosoiwoocommerce_tax_rates { get; set; }
        public DbSet<wp_kosoiwpsc_also_bought> wp_kosoiwpsc_also_bought { get; set; }
        public DbSet<wp_kosoiwpsc_cart_contents> wp_kosoiwpsc_cart_contents { get; set; }
        public DbSet<wp_kosoiwpsc_cart_item_meta> wp_kosoiwpsc_cart_item_meta { get; set; }
        public DbSet<wp_kosoiwpsc_checkout_forms> wp_kosoiwpsc_checkout_forms { get; set; }
        public DbSet<wp_kosoiwpsc_coupon_codes> wp_kosoiwpsc_coupon_codes { get; set; }
        public DbSet<wp_kosoiwpsc_currency_list> wp_kosoiwpsc_currency_list { get; set; }
        public DbSet<wp_kosoiwpsc_download_status> wp_kosoiwpsc_download_status { get; set; }
        public DbSet<wp_kosoiwpsc_meta> wp_kosoiwpsc_meta { get; set; }
        public DbSet<wp_kosoiwpsc_product_rating> wp_kosoiwpsc_product_rating { get; set; }
        public DbSet<wp_kosoiwpsc_purchase_logs> wp_kosoiwpsc_purchase_logs { get; set; }
        public DbSet<wp_kosoiwpsc_purchase_meta> wp_kosoiwpsc_purchase_meta { get; set; }
        public DbSet<wp_kosoiwpsc_region_tax> wp_kosoiwpsc_region_tax { get; set; }
        public DbSet<wp_kosoiwpsc_submited_form_data> wp_kosoiwpsc_submited_form_data { get; set; }
        public DbSet<wp_kosoiwpsc_visitor_meta> wp_kosoiwpsc_visitor_meta { get; set; }
        public DbSet<wp_kosoiwpsc_visitors> wp_kosoiwpsc_visitors { get; set; }
        public DbSet<wp_kosoiywrr_email_blocklist> wp_kosoiywrr_email_blocklist { get; set; }
        public DbSet<wp_kosoiywrr_email_schedule> wp_kosoiywrr_email_schedule { get; set; }
        public DbSet<wp_kosoipd_downloadlinks> wp_kosoipd_downloadlinks { get; set; }
        public DbSet<wp_kosoipd_files> wp_kosoipd_files { get; set; }
        public DbSet<wp_kosoipd_transactions> wp_kosoipd_transactions { get; set; }
        public DbSet<wp_kosoiwpsc_claimed_stock> wp_kosoiwpsc_claimed_stock { get; set; }
    }
}
