//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KosoyPerEntityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_kosoilayerslider
    {
        public int id { get; set; }
        public int author { get; set; }
        public string name { get; set; }
        public string slug { get; set; }
        public string data { get; set; }
        public int date_c { get; set; }
        public int date_m { get; set; }
        public bool flag_hidden { get; set; }
        public bool flag_deleted { get; set; }
    }
}
