//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KosoyPerEntityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_kosoiwpsc_purchase_logs
    {
        public decimal id { get; set; }
        public decimal totalprice { get; set; }
        public short statusno { get; set; }
        public string sessionid { get; set; }
        public string transactid { get; set; }
        public string authcode { get; set; }
        public decimal processed { get; set; }
        public Nullable<decimal> user_ID { get; set; }
        public string date { get; set; }
        public string gateway { get; set; }
        public string billing_country { get; set; }
        public string shipping_country { get; set; }
        public decimal base_shipping { get; set; }
        public string email_sent { get; set; }
        public string stock_adjusted { get; set; }
        public decimal discount_value { get; set; }
        public string discount_data { get; set; }
        public string track_id { get; set; }
        public string billing_region { get; set; }
        public string shipping_region { get; set; }
        public string find_us { get; set; }
        public string engravetext { get; set; }
        public string shipping_method { get; set; }
        public string shipping_option { get; set; }
        public string affiliate_id { get; set; }
        public string plugin_version { get; set; }
        public string notes { get; set; }
        public Nullable<decimal> wpec_taxes_total { get; set; }
        public Nullable<decimal> wpec_taxes_rate { get; set; }
    }
}
