//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KosoyPerEntityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_kosoiwpsc_currency_list
    {
        public decimal id { get; set; }
        public string country { get; set; }
        public string isocode { get; set; }
        public string currency { get; set; }
        public string symbol { get; set; }
        public string symbol_html { get; set; }
        public string code { get; set; }
        public string has_regions { get; set; }
        public string tax { get; set; }
        public string continent { get; set; }
        public string visible { get; set; }
    }
}
