//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KosoyPerEntityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_kosoiwpsc_also_bought
    {
        public decimal id { get; set; }
        public decimal selected_product { get; set; }
        public decimal associated_product { get; set; }
        public long quantity { get; set; }
    }
}
