//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KosoyPerEntityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_kosoiwpsc_cart_contents
    {
        public decimal id { get; set; }
        public decimal prodid { get; set; }
        public string name { get; set; }
        public decimal purchaseid { get; set; }
        public decimal price { get; set; }
        public decimal pnp { get; set; }
        public decimal tax_charged { get; set; }
        public decimal gst { get; set; }
        public long quantity { get; set; }
        public string donation { get; set; }
        public string no_shipping { get; set; }
        public string custom_message { get; set; }
        public string files { get; set; }
        public string meta { get; set; }
    }
}
