//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KosoyPerEntityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_kosoiywrr_email_schedule
    {
        public int id { get; set; }
        public long order_id { get; set; }
        public System.DateTime order_date { get; set; }
        public System.DateTime scheduled_date { get; set; }
        public string request_items { get; set; }
        public string mail_status { get; set; }
    }
}
