//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KosoyPerEntityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_kosoiwpsc_product_rating
    {
        public decimal id { get; set; }
        public string ipnum { get; set; }
        public decimal productid { get; set; }
        public bool rated { get; set; }
        public decimal time { get; set; }
    }
}
