//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KosoyPerEntityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_kosoiwpsc_coupon_codes
    {
        public decimal id { get; set; }
        public string coupon_code { get; set; }
        public decimal value { get; set; }
        public string is_percentage { get; set; }
        public string use_once { get; set; }
        public string is_used { get; set; }
        public string active { get; set; }
        public string every_product { get; set; }
        public System.DateTime start { get; set; }
        public System.DateTime expiry { get; set; }
        public string condition { get; set; }
    }
}
