//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KosoyPerEntityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_kosoiwoocommerce_arr_log
    {
        public long id { get; set; }
        public System.DateTime time { get; set; }
        public bool prio { get; set; }
        public string note { get; set; }
    }
}
