//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KosoyPerEntityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_kosoiwpsc_region_tax
    {
        public decimal id { get; set; }
        public decimal country_id { get; set; }
        public string name { get; set; }
        public string code { get; set; }
        public float tax { get; set; }
    }
}
