//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KosoyPerEntityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_kosoipd_files
    {
        public int id { get; set; }
        public string title { get; set; }
        public string filename { get; set; }
        public int uploaded { get; set; }
        public string filename_original { get; set; }
        public float price { get; set; }
        public string currency { get; set; }
        public int available_copies { get; set; }
        public string license_url { get; set; }
        public int registered { get; set; }
        public int deleted { get; set; }
    }
}
