//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KosoyPerEntityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_kosoipd_transactions
    {
        public int id { get; set; }
        public int file_id { get; set; }
        public string payer_name { get; set; }
        public string payer_email { get; set; }
        public float gross { get; set; }
        public string currency { get; set; }
        public string payment_status { get; set; }
        public string transaction_type { get; set; }
        public string details { get; set; }
        public int created { get; set; }
        public int deleted { get; set; }
    }
}
