//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KosoyPerEntityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_kosoiwpsc_download_status
    {
        public decimal id { get; set; }
        public Nullable<decimal> product_id { get; set; }
        public decimal fileid { get; set; }
        public decimal purchid { get; set; }
        public Nullable<decimal> cartid { get; set; }
        public string uniqueid { get; set; }
        public int downloads { get; set; }
        public string ip_number { get; set; }
        public string active { get; set; }
        public System.DateTime datetime { get; set; }
    }
}
