//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KosoyPerEntityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_kosoiwpsc_checkout_forms
    {
        public decimal id { get; set; }
        public string name { get; set; }
        public string type { get; set; }
        public string mandatory { get; set; }
        public string display_log { get; set; }
        public string @default { get; set; }
        public string active { get; set; }
        public long checkout_order { get; set; }
        public string unique_name { get; set; }
        public string options { get; set; }
        public string checkout_set { get; set; }
    }
}
