//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KosoyPerEntityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_kosoiwpsc_visitors
    {
        public decimal id { get; set; }
        public Nullable<decimal> user_id { get; set; }
        public Nullable<System.DateTime> last_active { get; set; }
        public Nullable<System.DateTime> expires { get; set; }
        public System.DateTime created { get; set; }
    }
}
