//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KosoyPerEntityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_kosoiwoocommerce_order_status_action
    {
        public int id { get; set; }
        public int term_id { get; set; }
        public int term_taxonomy_id { get; set; }
        public System.DateTime created { get; set; }
        public System.DateTime updated { get; set; }
        public string status_name { get; set; }
        public string status_icon { get; set; }
        public string status_color { get; set; }
        public string status_color_type { get; set; }
        public string sends_email { get; set; }
        public string display_completed { get; set; }
        public string display_processing { get; set; }
        public string can_cancel { get; set; }
        public string email_to { get; set; }
        public string email_subject { get; set; }
        public string from_name { get; set; }
        public string from_address { get; set; }
        public string display_essential_info { get; set; }
        public string display_custom_info { get; set; }
        public string custom_title { get; set; }
        public string custom_info { get; set; }
        public string payment_status { get; set; }
        public string action_icon { get; set; }
        public string display_for { get; set; }
        public string new_status { get; set; }
        public string status_slug { get; set; }
        public string status_label { get; set; }
        public string stock_status { get; set; }
        public string display_in_reports { get; set; }
        public string download_permitted { get; set; }
        public string custom_email_address { get; set; }
        public Nullable<bool> trigger_status { get; set; }
        public string statuses_trigger { get; set; }
        public string trigger_button_label { get; set; }
        public string hide_bulk_action { get; set; }
    }
}
