//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KosoyPerEntityDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class wp_kosoipd_downloadlinks
    {
        public int id { get; set; }
        public int file_id { get; set; }
        public string download_key { get; set; }
        public string owner { get; set; }
        public string source { get; set; }
        public int created { get; set; }
        public int deleted { get; set; }
    }
}
